# Generated by Django 5.0.6 on 2024-05-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages='Category is required and must be under 255 characters', max_length=255, unique=True)),
            ],
        ),
    ]
