# Generated by Django 5.0.6 on 2024-05-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_rename_name_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Task Title')),
                ('description', models.TextField(verbose_name='Task Description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is task completed?')),
                ('task_assigned', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='category.category', verbose_name='Task Category')),
            ],
        ),
    ]
